CREATE TABLE IF NOT EXISTS `#__airlines` (
  `id` int(10) NOT NULL auto_increment,
  `airlines` varchar(50) NOT NULL,
  `flight_number` varchar(20) NOT NULL,
  `source` varchar(40) NOT NULL,
  `destination` varchar(40) NOT NULL,
  `day1` varchar(10) NOT NULL,
  `time11` varchar(10) default NULL,
  `return11` varchar(10) default NULL,
  `time12` varchar(10) default NULL,
  `return12` varchar(10) default NULL,
  `time13` varchar(10) default NULL,
  `return13` varchar(10) default NULL,
  `time14` varchar(10) default NULL,
  `return14` varchar(10) default NULL,
  `time15` varchar(10) default NULL,
  `return15` varchar(10) default NULL,
  `time16` varchar(10) default NULL,
  `return16` varchar(10) default NULL,
  `time17` varchar(10) default NULL,
  `return17` varchar(10) default NULL,
  `day2` varchar(10) default NULL,
  `time21` varchar(10) default NULL,
  `return21` varchar(10) default NULL,
  `time22` varchar(10) default NULL,
  `return22` varchar(10) default NULL,
  `time23` varchar(10) default NULL,
  `return23` varchar(10) default NULL,
  `time24` varchar(10) default NULL,
  `return24` varchar(10) default NULL,
  `time25` varchar(10) default NULL,
  `return25` varchar(10) default NULL,
  `time26` varchar(10) default NULL,
  `return26` varchar(10) default NULL,
  `time27` varchar(10) default NULL,
  `return27` varchar(10) default NULL,
  `day3` varchar(10) default NULL,
  `time31` varchar(10) default NULL,
  `return31` varchar(10) default NULL,
  `time32` varchar(10) default NULL,
  `return32` varchar(10) default NULL,
  `time33` varchar(10) default NULL,
  `return33` varchar(10) default NULL,
  `time34` varchar(10) default NULL,
  `return34` varchar(10) default NULL,
  `time35` varchar(10) default NULL,
  `return35` varchar(10) default NULL,
  `time36` varchar(10) default NULL,
  `return36` varchar(10) default NULL,
  `time37` varchar(10) default NULL,
  `return37` varchar(10) default NULL,
  `day4` varchar(10) default NULL,
  `time41` varchar(10) default NULL,
  `return41` varchar(10) default NULL,
  `time42` varchar(10) default NULL,
  `return42` varchar(10) default NULL,
  `time43` varchar(10) default NULL,
  `return43` varchar(10) default NULL,
  `time44` varchar(10) default NULL,
  `return44` varchar(10) default NULL,
  `time45` varchar(10) default NULL,
  `return45` varchar(10) default NULL,
  `time46` varchar(10) default NULL,
  `return46` varchar(10) default NULL,
  `time47` varchar(10) default NULL,
  `return47` varchar(10) default NULL,
  `day5` varchar(10) default NULL,
  `time51` varchar(10) default NULL,
  `return51` varchar(10) default NULL,
  `time52` varchar(10) default NULL,
  `return52` varchar(10) default NULL,
  `time53` varchar(10) default NULL,
  `return53` varchar(10) default NULL,
  `time54` varchar(10) default NULL,
  `return54` varchar(10) default NULL,
  `time55` varchar(10) default NULL,
  `return55` varchar(10) default NULL,
  `time56` varchar(10) default NULL,
  `return56` varchar(10) default NULL,
  `time57` varchar(10) default NULL,
  `return57` varchar(10) default NULL,
  `day6` varchar(10) default NULL,
  `time61` varchar(10) default NULL,
  `return61` varchar(10) default NULL,
  `time62` varchar(10) default NULL,
  `return62` varchar(10) default NULL,
  `time63` varchar(10) default NULL,
  `return63` varchar(10) default NULL,
  `time64` varchar(10) default NULL,
  `return64` varchar(10) default NULL,
  `time65` varchar(10) default NULL,
  `return65` varchar(10) default NULL,
  `time66` varchar(10) default NULL,
  `return66` varchar(10) default NULL,
  `time67` varchar(10) default NULL,
  `return67` varchar(10) default NULL,
  `day7` varchar(10) default NULL,
  `time71` varchar(10) default NULL,
  `return71` varchar(10) default NULL,
  `time72` varchar(10) default NULL,
  `return72` varchar(10) default NULL,
  `time73` varchar(10) default NULL,
  `return73` varchar(10) default NULL,
  `time74` varchar(10) default NULL,
  `return74` varchar(10) default NULL,
  `time75` varchar(10) default NULL,
  `return75` varchar(10) default NULL,
  `time76` varchar(10) default NULL,
  `return76` varchar(10) default NULL,
  `time77` varchar(10) default NULL,
  `return77` varchar(10) default NULL,
  `economy` decimal(10,2) NOT NULL,
  `business` decimal(10,2) NOT NULL,
  `ceconomy` decimal(10,2) default NULL,
  `cbusiness` decimal(10,2) default NULL,
  `ieconomy` decimal(10,2) default NULL,
  `ibusiness` decimal(10,2) default NULL,
  `tax` decimal(10,2) default NULL,
  `serviceTax` varchar(3) default NULL,
  `seats` varchar(10) NOT NULL,
  `logo` varchar(30) default NULL,
  PRIMARY KEY  (`id`)
);

CREATE TABLE IF NOT EXISTS `#__booked` (
  `id` int(10) NOT NULL auto_increment,
  `flight_id` varchar(10) default NULL,
  `departure` date default NULL,
  `source` varchar(100) default NULL,
  `destination` varchar(100) default NULL,
  `time` varchar(10) default NULL,
  `seat1` varchar(30) default NULL,
  `seat2` varchar(30) default NULL,
  `seat3` varchar(30) default NULL,
  `seat4` varchar(30) default NULL,
  `seat5` varchar(30) default NULL,
  `seat6` varchar(30) default NULL,
  `seat7` varchar(30) default NULL,
  `seat8` varchar(30) default NULL,
  `seat9` varchar(30) default NULL,
  `seat10` varchar(30) default NULL,
  `seat11` varchar(30) default NULL,
  `seat12` varchar(30) default NULL,
  `seat13` varchar(30) default NULL,
  `seat14` varchar(30) default NULL,
  `seat15` varchar(30) default NULL,
  `seat16` varchar(30) default NULL,
  `seat17` varchar(30) default NULL,
  `seat18` varchar(30) default NULL,
  `seat19` varchar(30) default NULL,
  `seat20` varchar(30) default NULL,
  `seat21` varchar(30) default NULL,
  `seat22` varchar(30) default NULL,
  `seat23` varchar(30) default NULL,
  `seat24` varchar(30) default NULL,
  `seat25` varchar(30) default NULL,
  `seat26` varchar(30) default NULL,
  `seat27` varchar(30) default NULL,
  `seat28` varchar(30) default NULL,
  `seat29` varchar(30) default NULL,
  `seat30` varchar(30) default NULL,
  `seat31` varchar(30) default NULL,
  `seat32` varchar(30) default NULL,
  `seat33` varchar(30) default NULL,
  `seat34` varchar(30) default NULL,
  `seat35` varchar(30) default NULL,
  `seat36` varchar(30) default NULL,
  `seat37` varchar(30) default NULL,
  `seat38` varchar(30) default NULL,
  `seat39` varchar(30) default NULL,
  `seat40` varchar(30) default NULL,
  `seat41` varchar(30) default NULL,
  `seat42` varchar(30) default NULL,
  `seat43` varchar(30) default NULL,
  `seat44` varchar(30) default NULL,
  `seat45` varchar(30) default NULL,
  `seat46` varchar(30) default NULL,
  `seat47` varchar(30) default NULL,
  `seat48` varchar(30) default NULL,
  PRIMARY KEY  (`id`)
);

CREATE TABLE IF NOT EXISTS `#__customer` (
  `id` int(10) NOT NULL auto_increment,
  `title` varchar(10) NOT NULL,
  `firstname` varchar(60) default NULL,
  `lastname` varchar(60) default NULL,
  `address1` varchar(255) default NULL,
  `address2` varchar(255) default NULL,
  `city` varchar(60) default NULL,
  `state` varchar(60) default NULL,
  `country` varchar(60) default NULL,
  `zip` varchar(10) default NULL,
  `dob` varchar(20) default NULL,
  `mobile` varchar(20) default NULL,
  `alternate` varchar(20) default NULL,
  `email` varchar(80) default NULL,
  `price` decimal(40,2) default NULL,
  `payment` varchar(30) default NULL,
  `booked_on` date default NULL,
  `seat` varchar(60) default NULL,
  `return_seat` varchar(60) default NULL,
  PRIMARY KEY  (`id`)
);

CREATE TABLE IF NOT EXISTS `#__images` (
  `id` int(10) NOT NULL auto_increment,
  `airline_id` varchar(10) default NULL,
  `photo` varchar(60) default NULL,
  PRIMARY KEY  (`id`)
);

CREATE TABLE IF NOT EXISTS `#__leads` (
  `id` int(10) NOT NULL auto_increment,
  `customer_id` varchar(10) default NULL,
  `title` varchar(10) default NULL,
  `firstname` varchar(100) default NULL,
  `lastname` varchar(100) default NULL,
  `dob` varchar(30) default NULL,
  `type` varchar(100) default NULL,
  `seat` varchar(60) default NULL,
  `referrer` varchar(30) default NULL,
  `return_seat` varchar(60) default NULL,
  PRIMARY KEY  (`id`)
);