/*
 ### jQuery Star Rating Plugin v2.1 - 2008-03-12 ###
 By Diego A, http://www.fyneworks.com, diego@fyneworks.com
 - 'read only' feature by by Keith Wood, http://keith-wood.name/, kbwood@virginbroadband.com.au
 
 Project: http://plugins.jquery.com/project/MultipleFriendlyStarRating
 Website: http://www.fyneworks.com/jquery/star-rating/
	
	This is a modified version of the star rating plugin from:
 http://www.phpletter.com/Demo/Jquery-Star-Rating-Plugin/
  //BB: fixed bug with multiple ratings with same name but different forms
*/
eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}(';7(E)(6($){$.3={m:\'Z 10\',F:\'\',G:u,f:0,H:u,9:u,5:{},8:{w:6(n,a,b){4.g(n);$(a).I(\'.o\').J().p(\'11\'+(b||\'K\'))},g:6(n,a,b){$($.3.5[n].h).12(\'.o\').x(\'q\').x(\'13\')},j:6(n,a,b){7(!$($.3.5[n].k).14(\'.m\'))$($.3.5[n].k).I(\'.o\').J().p(\'q\')},l:6(n,a,b){$.3.5[n].k=a;r c=$(a).L(\'a\').M();$($.3.5[n].h).N(c);$.3.8.g(n);$.3.8.j(n);7(b.O)b.O.15($.3.5[n].h,[c,a])}}};$.16.3=6(d){7(4.P==0)y 4;d=$.Q({},$.3,d||{});4.17(6(i){r a=$.Q({},d||{},($.R?$(4).R():($.18?$(4).19():1a))||{});r n=$(4).1b(\'1c\').S(\'s\')+\'1d\'+4.s;7(!$.3.5[n])$.3.5[n]={z:0};i=$.3.5[n].z;$.3.5[n].z++;$.3.5[n].9=$.3.5[n].9||a.9||$(4).S(\'A\');7(i==0){$.3.5[n].h=$(\'<1e 1f="1g" s="\'+4.s+\'" B=""\'+(a.9?\' A="A"\':\'\')+\'>\');$(4).T($.3.5[n].h);7($.3.5[n].9||a.H){}U{$(4).T($(\'<t V="m"><a C="\'+a.m+\'">\'+a.F+\'</a></t>\').W(6(){$.3.8.g(n,4,a);$(4).p(\'q\')}).X(6(){$.3.8.j(n,4,a);$(4).x(\'q\')}).l(6(){$.3.8.l(n,4,a)}))}};e=$(\'<t V="o"><a C="\'+(4.C||4.B)+\'">\'+4.B+\'</a></t>\');$(4).1h(e);7(a.G)a.f=2;7(1i a.f==\'1j\'&&a.f>0){r b=(i%a.f),D=1k.1l($(e).Y()/a.f);$(e).Y(D).1m(\'a\').1n({\'1o-1p\':\'-\'+(b*D)+\'1q\'})};7($.3.5[n].9){$(e).p(\'1r\')}U{$(e).W(6(){$.3.8.g(n,4,a);$.3.8.w(n,4,\'K\')}).X(6(){$.3.8.g(n,4,a);$.3.8.j(n,4,a)}).l(6(){$.3.8.l(n,4,a)})};7(4.1s)$.3.5[n].k=e;$(4).1t();7(i+1==4.P)$.3.8.j(n,4,a)});1u(n 1v $.3.5)(6(c,v,n){7(!c)y;$.3.8.w(n,c,\'1w\');$(v).N($(c).L(\'a\').M())})($.3.5[n].k,$.3.5[n].h,n);y 4}})(E);',62,95,'|||rating|this|groups|function|if|event|readOnly|||||eStar|split|drain|valueElem||reset|current|click|cancel||star|addClass|star_on|var|name|div|false||fill|removeClass|return|count|disabled|value|title|spw|jQuery|cancelValue|half|required|prevAll|andSelf|hover|children|text|val|callback|length|extend|metadata|attr|before|else|class|mouseover|mouseout|width|Cancel|Rating|star_|siblings|star_hover|is|apply|fn|each|meta|data|null|parents|form|___|input|type|hidden|after|typeof|number|Math|floor|find|css|margin|left|px|star_readonly|checked|remove|for|in|on'.split('|'),0,{}))
